### ISSUE TITLE
需要规范章节标题的中文翻译

### ISSUE THREAD

**Issue by Geno1024** [LinuxStory/lfs-8.0-Chinese#6]
LFS 的每一个页面都有 Prev 和 Next，都需要用到章节标题的规范翻译，也许需要尽早规范一下，因为不会知道别人会怎么翻译他的标题，以后在这种小事上花太多时间不太好……

**Comment by bootingman** [comment]
约定：
1.出现第** 章章节名称统一成类似的格式 "第六章 安装基本系统软件"，中间是一个半角空格
2.章节的名称中如果是数字，比如5.4.2. **** 其中间的点号，保持原来的英文半角点号
